feat : WooCommerce Integration
frappe/ecommerce_integrations pull request #132
Opened 2021-12-06 13:39 UTC by aaronmenezes

-[ ] New module
-[ ] Basic migration (doctypes, utils)
-[ ] Use ecommerce item instead of custom fields
-[ ] Write patch to migrate existing users
-[ ] Remove integration from core

2021-12-14 17:04 UTC, ankush requested changes

2021-12-14 17:04 UTC, ankush commented on ecommerce_integrations/woocommerce/woocommerce_connection.py
> +		ordered_items_tax = item.get("total_tax")
This line should be moved nearer to where it's actually being used.

2021-12-14 17:04 UTC, ankush commented on ecommerce_integrations/woocommerce/woocommerce_connection.py
> +		order.get("shipping_total"),
Logically shipping costs should be added before shipping tax.

2021-12-14 17:06 UTC, ankush commented on ecommerce_integrations/woocommerce/woocommerce_connection.py
> +		order.get("shipping_total"),
Also IMO we should review tax computation thoroughly. There were several major issues with the current Shopify integration and I think this implementation of woocommerce taxes feels way to simple to be correct.

2021-12-15 05:17 UTC, ankush commented on ecommerce_integrations/woocommerce/doctype/woocommerce_setting/woocommerce_setting.py
> +			for doctype in ["Customer", "Sales Order", "Item", "Address"]:
```suggestion
			for doctype in ["Customer", "Sales Order", "Address"]:
```

If e-commerce item is being used then Item should not need a custom field now.

2022-01-27 14:18 UTC, ankush commented on ecommerce_integrations/woocommerce/doctype/woocommerce_setting/woocommerce_setting.py
> +from six.moves.urllib.parse import urlparse
removed now: https://github.com/frappe/frappe/pull/15763

2022-01-27 14:24 UTC, ankush commented on ecommerce_integrations/woocommerce/woocommerce_connection.py
> +from frappe.utils import cstr
```suggestion
from frappe.utils import cstr, flt
```

2022-02-08 10:54 UTC, aaronmenezes commented on ecommerce_integrations/woocommerce/woocommerce_connection.py
> +		frappe.throw(_("Please set Warehouse in Woocommerce Setting"))
Will remove this check and make Warehouse selection mandatory in woocommerce setting.

2022-04-28 11:44 UTC, closed without merging