Multiple payment gateways
frappe/ecommerce_integrations pull request #251
Opened 2023-07-01 08:21 UTC by meaziz

In shopify Integration 
Add support to multiple Payment Gateways that allows booking for payment for shopify orders across multiple accounts

This can be used for Cash on delivery, Credit Card payment etc...

2023-07-03 15:49 UTC, meaziz commented
@ankush  Can you provide your feedback to this?

2023-07-20 10:58 UTC, ankush requested changes

2023-07-20 10:58 UTC, ankush commented on ecommerce_integrations/shopify/invoice.py
> +	frappe.db.commit()
This shouldn't be added 

https://frappeframework.com/docs/v14/user/en/api/database#database-transaction-model

2023-07-20 10:58 UTC, ankush commented on ecommerce_integrations/shopify/invoice.py
> +	if len(shopify_order.get('payment_gateway_names')):
```suggestion
	if len(shopify_order and shopify_order.get('payment_gateway_names') or []):
```

Handle case when it's not sent.

2023-07-20 10:58 UTC, ankush commented on ecommerce_integrations/shopify/invoice.py
> +			if doc_gatewaty == gateway.get("gateway_name"):
`doc_gateway` won't be set if order didn't have any. You'll get `'UnboundVariableError'`.

2023-07-20 10:58 UTC, ankush commented on ecommerce_integrations/ecommerce_integrations/doctype/payment_gateways/payment_gateways.json
> + "name": "Payment Gateways",
Let's rename this to something that won't crash with others. `Shopify Payment Gateways`?

2023-10-31 12:15 UTC, ankush commented
reopen when ready

2023-10-31 12:15 UTC, closed without merging